version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-deps
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:
          name: Run eslint validation
          command: npm run eslint src
      - run:
          name: Background the app
          command: npm start
          background: true
      - run:
          name: Run E2E tests
          command: npm run cypress run --record
          when: on_success